export const prompts = [
	"A horse in a field at sunrise with a rainbow in the background",
	"An award-winning professional photo of a marmot skiing in the Alps",
  "A baby eating an apple on a hill during the day",
  "A sheep eating a box on a hill during the day",
  "A horse using an apple in a pond at night",
  "A child making a box next to the white house during the day",
  "A man making a car near a waterfall during christmas",
  "A lion using a car next to the white house in the morning",
  "A cat using a box on a hill during christmas",
  "A sheep sitting on a pizza in a sunset during the day",
  "A woman making a pizza in a pond during christmas",
  "A dog making a pizza in a sunset in the morning",
  "An elephant sitting on a whiteboard near a waterfall during the day",
  "A horse using a whiteboard in a pond during the day",
  "A baby using an apple under a rainbow during the day",
  "A child using a cookie in a sunset during christmas",
  "A lion making an avocado under a rainbow during the day",
  "A child making a plant in a sunset in the morning",
  "A bird using an apple in a pond during the day",
  "A lion sitting on a box near a waterfall in the morning",
  "A tiger eating a box under a rainbow at night",
  "A bird using a pizza under a rainbow at night",
  "A cat sitting on a book next to the white house at night",
  "A sheep eating an avocado in a pond in the morning",
  "An elephant using an apple under a rainbow in the morning",
  "A tiger eating a whiteboard next to the white house during christmas",
  "A wolf sitting on a car under a rainbow during christmas",
  "A woman sitting on a car in a pond during the day",
  "A woman making a book near a waterfall during the day",
  "An elephant eating a car under a rainbow at night",
  "A baby using an avocado on a hill during christmas",
  "A human eating a box in a sunset at night",
  "A dog making an avocado near a waterfall during the day",
  "A dog sitting on a cookie near a waterfall at night",
  "A fox making an avocado under a rainbow in the morning",
  "A cat using an avocado near a waterfall in the morning",
  "A snake sitting on a book on a hill during the day",
  "A wolf making a cookie in a sunset during christmas",
  "A bird using a plant on a hill during christmas",
  "A cat sitting on an apple in a sunset during the day",
  "A fox eating a plant under a rainbow during christmas",
  "A child making a pizza on a hill during christmas",
  "A tiger eating an avocado in a sunset at night",
  "A tiger making a pizza next to the white house during the day",
  "A baby eating an apple under a rainbow during christmas",
  "A sheep sitting on an apple near a waterfall during christmas",
  "A child using a plant near a waterfall in the morning",
  "A child making a cookie in a pond in the morning",
  "A cat sitting on a plant in a sunset during christmas",
  "A snake making a pizza under a rainbow in the morning",
  "An elephant using a plant near a waterfall during christmas",
  "A tiger eating a whiteboard near a waterfall at night",
  "A baby making an apple next to the white house in the morning",
  "A child making a box next to the white house in the morning",
  "A child using a book next to the white house during the day",
  "A woman eating a car in a sunset during the day",
  "A horse eating a pizza on a hill during the day",
  "A snake eating an apple on a hill during christmas",
  "A horse making a pizza in a pond in the morning",
  "A bird using a cookie near a waterfall during christmas",
  "An elephant making a book in a sunset at night",
  "A woman eating a plant in a sunset during the day",
  "A cat using a cookie in a sunset at night",
  "A bird eating an avocado near a waterfall during the day",
  "An elephant making a plant next to the white house at night",
  "A cat eating a plant in a sunset at night",
  "A wolf making a cookie near a waterfall at night",
  "A cat using a car next to the white house during the day",
  "A lion sitting on a car near a waterfall during the day",
  "An elephant making an apple under a rainbow during christmas",
  "A tiger sitting on a pizza near a waterfall in the morning",
  "A horse making a whiteboard near a waterfall during the day",
  "A baby making an apple in a pond in the morning",
  "A fox sitting on a book on a hill during the day",
  "A snake making a plant near a waterfall at night",
  "A fox eating a cookie on a hill in the morning",
  "A dog eating an apple near a waterfall during christmas",
  "A lion eating a box on a hill during christmas",
  "A snake using a car on a hill in the morning",
  "A horse making a plant under a rainbow at night",
  "A woman making a plant in a pond during christmas",
  "A cat making a cookie under a rainbow at night",
  "A horse sitting on a cookie in a sunset in the morning",
  "A man eating a whiteboard near a waterfall during the day",
  "A sheep using an apple in a pond during the day",
  "A child sitting on a whiteboard next to the white house at night",
  "A baby sitting on an avocado on a hill in the morning",
  "A sheep using an apple in a pond during the day",
  "A man eating a book in a pond at night",
  "A horse sitting on a whiteboard in a pond during christmas",
  "A child eating a plant under a rainbow during the day",
  "A sheep eating an avocado near a waterfall during christmas",
  "A human sitting on an avocado in a pond during the day",
  "A sheep using a cookie near a waterfall at night",
  "A sheep sitting on a pizza in a sunset during christmas",
  "A child eating a pizza next to the white house at night",
  "A tiger making a car in a sunset in the morning",
  "An elephant making a pizza on a hill during the day",
  "A fox sitting on an avocado next to the white house during christmas",
  "A lion eating a box under a rainbow in the morning",
];
